// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzdL72JhQ213lFBacUFFcpM2hPDktNHvo',
    appId: '1:391556124095:web:30d0cb0a62de7ecfb7250a',
    messagingSenderId: '391556124095',
    projectId: 'autism-support-eff9a',
    authDomain: 'autism-support-eff9a.firebaseapp.com',
    storageBucket: 'autism-support-eff9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQGqahcWCnOItsnvgBU-TnuXByX1j2lTI',
    appId: '1:391556124095:android:fbc7b32770e0b04fb7250a',
    messagingSenderId: '391556124095',
    projectId: 'autism-support-eff9a',
    storageBucket: 'autism-support-eff9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbdHeGKrvzTriBwitBS7DcKn9PLMhW-3w',
    appId: '1:391556124095:ios:6e2b8f28c21d64eab7250a',
    messagingSenderId: '391556124095',
    projectId: 'autism-support-eff9a',
    storageBucket: 'autism-support-eff9a.appspot.com',
    iosBundleId: 'com.example.autismSupport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbdHeGKrvzTriBwitBS7DcKn9PLMhW-3w',
    appId: '1:391556124095:ios:6e2b8f28c21d64eab7250a',
    messagingSenderId: '391556124095',
    projectId: 'autism-support-eff9a',
    storageBucket: 'autism-support-eff9a.appspot.com',
    iosBundleId: 'com.example.autismSupport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzdL72JhQ213lFBacUFFcpM2hPDktNHvo',
    appId: '1:391556124095:web:9cc2b5ca186bd0a2b7250a',
    messagingSenderId: '391556124095',
    projectId: 'autism-support-eff9a',
    authDomain: 'autism-support-eff9a.firebaseapp.com',
    storageBucket: 'autism-support-eff9a.appspot.com',
  );
}
